### Create project

POST http://localhost:3333/projects
Content-Type: application/json

{
  "name": "",
  "description": "",
  "gitHubUrl": "",
  "publishedAt": "",
  "thumbnailUrl": "",
  "stackIds": []
}


### Delete project

DELETE http://localhost:3333/projects/:id


### Get project by ID

GET http://localhost:3333/projects/:id


### Get projects

GET http://localhost:3333/projects


### Update project

PUT http://localhost:3333/projects/:id
Content-Type: application/json

{
  "name": "",
  "description": "",
  "gitHubUrl": "",
  "publishedAt": "",
  "thumbnailUrl": "",
  "stackIds": []
}